### ISSUE TITLE
I would like to know your experimental environment.

### ISSUE THREAD

**Issue by shuaizhao95** [zhaopku/nlp_geometry_attack#1]
I would like to know your experimental environment because the results I reproduced are very bad.

The accuracy of IMBD is about 50%

**Comment by sullendhy** [comment]
The same! Why?

**Comment by zhaopku** [comment]
Hi, we are aware that some detailed hyper-parameters are missing. At this point this implementation is obsolete and provided as it is.

But soon we will release a new implementation which is adapted to modern architectures like BERT. Thanks again for your interest!
